export const environment = {
  production: false,
  APP_ID: 'REPLACE_APP_ID',
  AUTH_KEY: 'REPLACE_APP_AUTH_KEY',
  AUTH_SECRET: 'REPLACE_APP_AUTH_SECRET',
  CONFERENCE_SERVER_ENDPOINT: 'wss://REPLACE_APP_JANUS_DOMAIN:8989',
  CHAT_ENDPOINT: 'REPLACE_APP_CHAT_DOMAIN',
  API_ENDPOINT: 'REPLACE_APP_API_DOMAIN',
  newOne: true
};
